//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TqtTaikhoan
    {
        public string TqtId { get; set; }
        public string TqtUser { get; set; }
        public string TqtPass { get; set; }
        public string TqtName { get; set; }
        public Nullable<int> TqtAge { get; set; }
        public string TqtEmail { get; set; }
        public string TqtPhone { get; set; }
        public Nullable<bool> TqtStatus { get; set; }
    }
}
