//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TqtLession7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tqtlesson07Entities : DbContext
    {
        public Tqtlesson07Entities()
            : base("name=Tqtlesson07Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tqtkhoa> Tqtkhoas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
