//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TqtLession7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tqtkhoa
    {
        public string TqtMakh { get; set; }
        public string TqtTenkh { get; set; }
        public Nullable<bool> TqtTrangthai { get; set; }
    }
}
