//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TqtSinhvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ketqua
    {
        public int MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual Monho Monho { get; set; }
        public virtual TqtSinhvien TqtSinhvien { get; set; }
    }
}
