//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TqtSinhvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TqtKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TqtKhoa()
        {
            this.TqtSinhviens = new HashSet<TqtSinhvien>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TqtSinhvien> TqtSinhviens { get; set; }
    }
}
