//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TqtSinhvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TqtSinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TqtSinhvien()
        {
            this.Ketquas = new HashSet<Ketqua>();
        }
    
        public int MaSV { get; set; }
        public string HoSV { get; set; }
        public string TenSV { get; set; }
        public Nullable<bool> Phai { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Noisinh { get; set; }
        public string MaKh { get; set; }
        public Nullable<decimal> Hocbong { get; set; }
        public Nullable<double> Diemtrungbinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ketqua> Ketquas { get; set; }
        public virtual TqtKhoa TqtKhoa { get; set; }
    }
}
