//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvcK22CNT1Lesson11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvcTaiKhoan
    {
        public int TvcId { get; set; }
        public string TvcUserName { get; set; }
        public string TvcPassword { get; set; }
        public string TvcFullName { get; set; }
        public Nullable<int> TvcAge { get; set; }
        public string TvcEmail { get; set; }
        public string TvcPhone { get; set; }
        public Nullable<bool> TvcStatus { get; set; }
    }
}
